<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div data-block="minicompare" class="minicompare">
    <a href=""  class="showcompare"><span>Compare</span></a>  
    <div class="block block-minicompare"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
                    "appendTo":"[data-block=minicompare]",
                    "triggerTarget":".showcompare",
                    "timeout": "2000",
                    "closeOnMouseLeave": false,
                    "closeOnEscape": true,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":[]}}'>
                    <div id="minicompare-content-wrapper">
                            Compare Products
                    </div>
        </div>  
</div>
    

