<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div data-block="minilogin" class="minilogin">
        <a href="<?php echo $block->getUrl('customer/account/login'); ?>" class="showlogin"><span class="label"><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></a>    
        <div class="block block-minilogin"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
                    "appendTo":"[data-block=minilogin]",
                    "triggerTarget":".showlogin",
                    "timeout": "2000",
                    "closeOnMouseLeave": false,
                    "closeOnEscape": true,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":[]}}'>
                    <div id="minilogin-content-wrapper">
                            <div class="block-title">
                                <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Sign In') ?></strong>
                            </div>
                            <div class="block-content" aria-labelledby="block-customer-login-heading">
                                <form class="form form-login"
                                      action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                                      method="post"
                                      id="login-form"
                                      data-mage-init='{"validation":{}}'>
                                    <?php echo $block->getBlockHtml('formkey'); ?>
                                    <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                                        <div class="field email required">
                                                <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>">
                                        </div>
                                        <div class="field password required">
                                                <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}" placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>">
                                        </div>
                                        <?php echo $block->getChildHtml('form_additional_info'); ?>
                                        <div class="actions-toolbar">
                                            <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>
                                            <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
                                        </div>
                                    </fieldset>
                                </form>
                            </div>
                    </div>
        </div>
</div>
    

